
   
name: archaeology-papers-with-code
 
on: 
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run archaepaperswithcode manually'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'benmarwick',
            repo: 'archaepaperswithcode',
            workflow_id: 'archaepaperswithcode.yml',
            ref: 'main'
          })
  
